name: CI
on: [push, pull_request]
jobs:
  offline-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke test
        run: ./scripts/smoke.sh
  full-test:
    needs: offline-check
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: npm --prefix frontend ci
      - run: npm --prefix frontend run lint
      - run: npm --prefix frontend test
